version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jamessheppard
      POSTGRES_PASSWORD: password
      POSTGRES_DB: golang_website
    ports:
      - '127.0.0.1:5432:5432'

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080
