version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      HOST: localhost
      POSTGRES_USER: jamessheppard
      POSTGRES_PASSWORD: password
      POSTGRES_DB: golang_website
    ports:
      - 5432:5432
  web:
    build: ./Dockerfile
    # command: ['./scripts/wait-for-it.sh', 'db:5432', '--', 'go', 'run', 'main.go']
    command: ['ls']
    ports:
      - '3000:3080'
    depends_on:
      - db
    links:
      - db

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080
